[package]
name = "concurrent_server"
version = "0.1.0"
edition = "2021"

[dependencies]
mime_guess = "2.0"
reqwest = "0.11"

[dev-dependencies]
reqwest = { version = "0.11", features = ["blocking"] }

